import './globals.css'
import { Inter_Tight } from 'next/font/google'

export const InterTight = Inter_Tight({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  fallback: [ "Arial"],
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={InterTight.className}>{children}</body>
    </html>
  )
}
